from django.db import models
from django.contrib.auth.hashers import make_password, check_password
from uuid import uuid4
from contacts import models as contact_model

class User(models.Model):
    name = models.CharField(max_length=255)
    phone_no = models.CharField(max_length=20, unique=True) 
    code= models.CharField(max_length=10)
    email = models.EmailField(unique=True)  
    password = models.CharField(max_length=128)  
    # autogenerated id (int)

    def save(self, *args, **kwargs):
        if self.password:
            self.password = make_password(self.password)  
        super().save(*args, **kwargs)
        contact = contact_model.Contacts.objects.create(
            name=self.name,
            phone_no=self.phone_no,
            code=self.code,
            is_spam=False,
            is_registered=True,
            user_id=self.id,  
            email=self.email
        )

    def check_password(self, password):
        return check_password(password, self.password)  

    class Meta:
        db_table = 'users' 

